name: Prettier

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Prettier linting
    runs-on: ubuntu-latest

    steps:
      - name: Prettier Action
        uses: creyD/prettier_action@v3.3
