name: Prettier

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Prettier linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Prettier Action
        uses: creyD/prettier_action@v3.3
